name: app_customizer
description: "Easy way to customize application colors, pixels, borders, alignment etc. from root instance."
version: 1.0.4
repository: https://github.com/Mohiuddin655-PUB/app_customizer.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  app_color: ^1.0.4
  app_dimen: ^1.0.7
  flutter_device_config: ^1.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: